name: CI

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  linux:
    name: Linux Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust with musl target
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-musl
    
    - name: Install musl tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-musl-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run clippy
      run: cargo clippy --target x86_64-unknown-linux-musl -- -D warnings
    
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl
    
    - name: Run tests
      run: cargo test --target x86_64-unknown-linux-musl
    
    - name: Build release
      if: startsWith(github.ref, 'refs/tags/')
      run: cargo build --release --target x86_64-unknown-linux-musl
    
    - name: Strip binary
      if: startsWith(github.ref, 'refs/tags/')
      run: strip target/x86_64-unknown-linux-musl/release/suricasta-rules
    
    - name: Rename binary for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p release-artifacts
        cp target/x86_64-unknown-linux-musl/release/suricasta-rules release-artifacts/suricasta-rules-linux-x86_64
    
    - name: Upload Linux binary
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: suricasta-rules-linux-x86_64
        path: release-artifacts/suricasta-rules-linux-x86_64

  windows-cross:
    name: Windows Cross-Compilation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-gnu
    
    - name: Install MinGW-w64
      run: sudo apt-get update && sudo apt-get install -y mingw-w64
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-windows-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-windows-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-windows-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build for Windows
      run: cargo build --target x86_64-pc-windows-gnu --verbose
    
    - name: Build release for Windows
      if: startsWith(github.ref, 'refs/tags/')
      run: cargo build --release --target x86_64-pc-windows-gnu --verbose
    
    - name: Strip binary
      if: startsWith(github.ref, 'refs/tags/')
      run: x86_64-w64-mingw32-strip target/x86_64-pc-windows-gnu/release/suricasta-rules.exe
    
    - name: Rename binary for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p release-artifacts
        cp target/x86_64-pc-windows-gnu/release/suricasta-rules.exe release-artifacts/suricasta-rules-windows-x86_64.exe
    
    - name: Upload Windows binary
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: suricasta-rules-windows-x86_64
        path: release-artifacts/suricasta-rules-windows-x86_64.exe

  # A rule Windows build job, however we don't use this for the
  # release binary.
  windows:
    name: Windows Build and Test
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run clippy
      run: cargo clippy -- -D warnings
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose

    - name: Rename debug binary
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path build-artifacts
        Copy-Item target/debug/suricasta-rules.exe build-artifacts/suricasta-rules-windows-debug-x86_64.exe

    - name: Upload debug binary
      uses: actions/upload-artifact@v4
      with:
        name: suricasta-rules-windows-debug-x86_64
        path: build-artifacts/suricasta-rules-windows-debug-x86_64.exe

  # Depends on "windows", just to make sure the tests pass.
  release:
    name: Create Release
    needs: [linux, windows-cross, windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: suricasta-rules-linux-x86_64
        path: release-artifacts/
    
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: suricasta-rules-windows-x86_64
        path: release-artifacts/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-artifacts/suricasta-rules-linux-x86_64
          release-artifacts/suricasta-rules-windows-x86_64.exe
        draft: false
        prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
